//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_pcvrset : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean time_forward
        {
            get
            {
                return SteamVR_Actions.pcvrset_time_forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean month_forward
        {
            get
            {
                return SteamVR_Actions.pcvrset_month_forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean month_back
        {
            get
            {
                return SteamVR_Actions.pcvrset_month_back;
            }
        }
        
        public virtual SteamVR_Action_Boolean time_back
        {
            get
            {
                return SteamVR_Actions.pcvrset_time_back;
            }
        }
        
        public virtual SteamVR_Action_Boolean rise
        {
            get
            {
                return SteamVR_Actions.pcvrset_rise;
            }
        }
        
        public virtual SteamVR_Action_Boolean fall
        {
            get
            {
                return SteamVR_Actions.pcvrset_fall;
            }
        }
    }
}
